// src/context/LanguageContext.jsx
// ──────────────────────────────────────────────────────────────────────────────
// USAGE:
//   1. Wrap your App (or index.jsx) with <LanguageProvider>
//      import { LanguageProvider } from "./context/LanguageContext";
//      <LanguageProvider><App /></LanguageProvider>
//
//   2. In any component use the hook:
//      import { useLanguage } from "./context/LanguageContext";
//      const { t, lang, setLang, languages } = useLanguage();
//      <h1>{t("hero.title")}</h1>
// ──────────────────────────────────────────────────────────────────────────────

import { createContext, useContext, useState } from "react";

// ── All supported languages ──
export const languages = [
  { code: "en", label: "English",    flag: "🇬🇧" },
  { code: "hi", label: "हिंदी",       flag: "🇮🇳" },
  { code: "mr", label: "मराठी",       flag: "🇮🇳" },
  { code: "gu", label: "ગુજરાતી",    flag: "🇮🇳" },
  { code: "ta", label: "தமிழ்",       flag: "🇮🇳" },
  { code: "te", label: "తెలుగు",      flag: "🇮🇳" },
  { code: "ar", label: "العربية",     flag: "🇸🇦" },
  { code: "fr", label: "Français",    flag: "🇫🇷" },
  { code: "de", label: "Deutsch",     flag: "🇩🇪" },
  { code: "es", label: "Español",     flag: "🇪🇸" },
  { code: "zh", label: "中文",         flag: "🇨🇳" },
  { code: "ja", label: "日本語",       flag: "🇯🇵" },
];

// ── Translations ──
const translations = {
  en: {
    nav: {
      home: "Home", features: "Features", solutions: "Solutions",
      resources: "Resources", about: "About Us", contact: "Contact",
      getStarted: "Get Started",
    },
    hero: {
      badge: "Smart. Secure. Simplified.",
      title: "Manage Documents",
      titleHighlight: "Smarter",
      subtitle: "Store, organize, and access all your documents securely from one centralized platform. Improve productivity and collaboration across your organization.",
      btnStart: "Get Started",
      btnDemo: "Watch Demo",
      badge1: "Secure & Compliant",
      badge2: "Access Anywhere",
      badge3: "Scalable Solution",
    },
    about: {
      badge: "Our Story",
      title: "Built for Modern",
      titleHighlight: "Document Management",
      subtitle: "We started DMS with a simple belief — managing documents should be effortless, not a daily struggle.",
      mission: "Our Mission",
      missionText: "To empower organizations with a secure, intelligent, and easy-to-use document management platform that scales with their growth.",
      vision: "Our Vision",
      visionText: "A world where information flows freely and securely across teams — no lost files, no version chaos, no compliance headaches.",
      team: "Meet the Team",
      teamSubtitle: "A passionate group of engineers, designers, and product thinkers committed to building great software.",
      values: "Our Values",
      security: "Security First",
      securityDesc: "Every feature is built with data protection at its core.",
      simplicity: "Radical Simplicity",
      simplicityDesc: "Powerful features that anyone can use on day one.",
      reliability: "Always Reliable",
      reliabilityDesc: "99.9% uptime SLA with enterprise-grade infrastructure.",
      innovation: "Continuous Innovation",
      innovationDesc: "We ship improvements every week, driven by user feedback.",
      stat1: "Documents Managed",
      stat2: "Active Teams",
      stat3: "Countries",
      stat4: "Uptime",
    },
    contact: {
      badge: "Get in Touch",
      title: "We'd love to",
      titleHighlight: "hear from you",
      subtitle: "Have questions, feedback, or just want to say hello? Our team is here to help.",
      name: "Full Name",
      namePlaceholder: "Enter your name",
      email: "Email Address",
      emailPlaceholder: "you@company.com",
      subject: "Subject",
      subjectPlaceholder: "How can we help?",
      message: "Message",
      messagePlaceholder: "Tell us more about your query...",
      send: "Send Message",
      sending: "Sending...",
      success: "Message sent! We'll get back to you within 24 hours.",
      info: "Contact Information",
      emailLabel: "Email Us",
      phoneLabel: "Call Us",
      addressLabel: "Office",
      address: "123 Tech Park, Sector 5, Mumbai 400001, India",
      hours: "Business Hours",
      hoursVal: "Mon – Fri, 9 AM – 6 PM IST",
    },
    footer: {
      privacy: "Privacy Policy",
      terms: "Terms of Service",
      support: "Support",
      contact: "Contact",
      rights: "All rights reserved.",
    },
  },

  hi: {
    nav: {
      home: "होम", features: "विशेषताएं", solutions: "समाधान",
      resources: "संसाधन", about: "हमारे बारे में", contact: "संपर्क",
      getStarted: "शुरू करें",
    },
    hero: {
      badge: "स्मार्ट। सुरक्षित। सरल।",
      title: "दस्तावेज़ प्रबंधन करें",
      titleHighlight: "स्मार्ट तरीके से",
      subtitle: "अपने सभी दस्तावेज़ एक केंद्रीय प्लेटफ़ॉर्म से सुरक्षित रूप से स्टोर, व्यवस्थित और एक्सेस करें।",
      btnStart: "शुरू करें",
      btnDemo: "डेमो देखें",
      badge1: "सुरक्षित और अनुपालन",
      badge2: "कहीं से भी एक्सेस",
      badge3: "स्केलेबल समाधान",
    },
    about: {
      badge: "हमारी कहानी",
      title: "बनाया गया आधुनिक",
      titleHighlight: "दस्तावेज़ प्रबंधन के लिए",
      subtitle: "हमने DMS एक सरल विश्वास के साथ शुरू किया — दस्तावेज़ प्रबंधन आसान होना चाहिए।",
      mission: "हमारा मिशन",
      missionText: "संगठनों को एक सुरक्षित, बुद्धिमान और उपयोग में आसान दस्तावेज़ प्रबंधन प्लेटफ़ॉर्म से सशक्त बनाना।",
      vision: "हमारा विज़न",
      visionText: "एक ऐसी दुनिया जहां जानकारी टीमों में स्वतंत्र और सुरक्षित रूप से प्रवाहित हो।",
      team: "हमारी टीम",
      teamSubtitle: "इंजीनियर, डिज़ाइनर और उत्पाद विशेषज्ञों का एक जुनूनी समूह।",
      values: "हमारे मूल्य",
      security: "सुरक्षा पहले",
      securityDesc: "हर सुविधा डेटा सुरक्षा को ध्यान में रखकर बनाई गई है।",
      simplicity: "सरलता",
      simplicityDesc: "शक्तिशाली सुविधाएं जो कोई भी पहले दिन उपयोग कर सकता है।",
      reliability: "हमेशा विश्वसनीय",
      reliabilityDesc: "99.9% अपटाइम SLA के साथ एंटरप्राइज़-ग्रेड इंफ्रास्ट्रक्चर।",
      innovation: "निरंतर नवाचार",
      innovationDesc: "हम हर हफ्ते उपयोगकर्ता की प्रतिक्रिया से बेहतरी करते हैं।",
      stat1: "प्रबंधित दस्तावेज़",
      stat2: "सक्रिय टीमें",
      stat3: "देश",
      stat4: "अपटाइम",
    },
    contact: {
      badge: "संपर्क करें",
      title: "हमें खुशी होगी",
      titleHighlight: "आपसे सुनकर",
      subtitle: "कोई सवाल, सुझाव या बस हैलो कहना चाहते हैं? हमारी टीम यहाँ है।",
      name: "पूरा नाम",
      namePlaceholder: "अपना नाम दर्ज करें",
      email: "ईमेल पता",
      emailPlaceholder: "you@company.com",
      subject: "विषय",
      subjectPlaceholder: "हम कैसे मदद कर सकते हैं?",
      message: "संदेश",
      messagePlaceholder: "अपनी जानकारी हमें बताएं...",
      send: "संदेश भेजें",
      sending: "भेज रहे हैं...",
      success: "संदेश भेजा गया! हम 24 घंटे में जवाब देंगे।",
      info: "संपर्क जानकारी",
      emailLabel: "ईमेल करें",
      phoneLabel: "कॉल करें",
      addressLabel: "कार्यालय",
      address: "123 टेक पार्क, सेक्टर 5, मुंबई 400001, भारत",
      hours: "व्यापार के घंटे",
      hoursVal: "सोम – शुक्र, सुबह 9 – शाम 6 IST",
    },
    footer: {
      privacy: "गोपनीयता नीति",
      terms: "सेवा की शर्तें",
      support: "सहायता",
      contact: "संपर्क",
      rights: "सर्वाधिकार सुरक्षित।",
    },
  },

  fr: {
    nav: {
      home: "Accueil", features: "Fonctionnalités", solutions: "Solutions",
      resources: "Ressources", about: "À propos", contact: "Contact",
      getStarted: "Commencer",
    },
    hero: {
      badge: "Intelligent. Sécurisé. Simplifié.",
      title: "Gérez vos documents",
      titleHighlight: "plus intelligemment",
      subtitle: "Stockez, organisez et accédez à tous vos documents en toute sécurité depuis une plateforme centralisée.",
      btnStart: "Commencer",
      btnDemo: "Voir la démo",
      badge1: "Sécurisé et Conforme",
      badge2: "Accès Partout",
      badge3: "Solution Évolutive",
    },
    about: {
      badge: "Notre Histoire",
      title: "Conçu pour la gestion moderne",
      titleHighlight: "des documents",
      subtitle: "Nous avons créé DMS avec une conviction simple — gérer des documents doit être facile.",
      mission: "Notre Mission",
      missionText: "Donner aux organisations une plateforme de gestion documentaire sécurisée, intelligente et facile à utiliser.",
      vision: "Notre Vision",
      visionText: "Un monde où l'information circule librement et en toute sécurité entre les équipes.",
      team: "Notre Équipe",
      teamSubtitle: "Un groupe passionné d'ingénieurs, designers et experts produit.",
      values: "Nos Valeurs",
      security: "Sécurité Avant Tout",
      securityDesc: "Chaque fonctionnalité est conçue avec la protection des données au cœur.",
      simplicity: "Simplicité Radicale",
      simplicityDesc: "Des fonctionnalités puissantes que tout le monde peut utiliser dès le premier jour.",
      reliability: "Toujours Fiable",
      reliabilityDesc: "SLA de disponibilité de 99,9% avec une infrastructure de niveau entreprise.",
      innovation: "Innovation Continue",
      innovationDesc: "Nous améliorons chaque semaine grâce aux retours utilisateurs.",
      stat1: "Documents Gérés",
      stat2: "Équipes Actives",
      stat3: "Pays",
      stat4: "Disponibilité",
    },
    contact: {
      badge: "Contactez-nous",
      title: "Nous serions ravis",
      titleHighlight: "d'avoir de vos nouvelles",
      subtitle: "Des questions, des commentaires ou juste envie de dire bonjour ? Notre équipe est là.",
      name: "Nom Complet",
      namePlaceholder: "Entrez votre nom",
      email: "Adresse Email",
      emailPlaceholder: "vous@entreprise.com",
      subject: "Sujet",
      subjectPlaceholder: "Comment pouvons-nous vous aider ?",
      message: "Message",
      messagePlaceholder: "Dites-nous en plus sur votre demande...",
      send: "Envoyer le message",
      sending: "Envoi en cours...",
      success: "Message envoyé ! Nous vous répondrons dans les 24 heures.",
      info: "Informations de Contact",
      emailLabel: "Nous écrire",
      phoneLabel: "Nous appeler",
      addressLabel: "Bureau",
      address: "123 Tech Park, Secteur 5, Mumbai 400001, Inde",
      hours: "Heures d'ouverture",
      hoursVal: "Lun – Ven, 9h – 18h IST",
    },
    footer: {
      privacy: "Politique de Confidentialité",
      terms: "Conditions d'Utilisation",
      support: "Support",
      contact: "Contact",
      rights: "Tous droits réservés.",
    },
  },

  de: {
    nav: {
      home: "Startseite", features: "Funktionen", solutions: "Lösungen",
      resources: "Ressourcen", about: "Über uns", contact: "Kontakt",
      getStarted: "Loslegen",
    },
    hero: {
      badge: "Intelligent. Sicher. Vereinfacht.",
      title: "Dokumente verwalten",
      titleHighlight: "intelligenter",
      subtitle: "Speichern, organisieren und greifen Sie sicher auf alle Ihre Dokumente von einer zentralen Plattform aus zu.",
      btnStart: "Loslegen",
      btnDemo: "Demo ansehen",
      badge1: "Sicher & Konform",
      badge2: "Überall Zugriff",
      badge3: "Skalierbare Lösung",
    },
    about: {
      badge: "Unsere Geschichte",
      title: "Entwickelt für modernes",
      titleHighlight: "Dokumentenmanagement",
      subtitle: "Wir haben DMS mit einer einfachen Überzeugung gestartet — Dokumente verwalten sollte mühelos sein.",
      mission: "Unsere Mission",
      missionText: "Organisationen mit einer sicheren, intelligenten und einfach zu bedienenden Dokumentenmanagement-Plattform zu stärken.",
      vision: "Unsere Vision",
      visionText: "Eine Welt, in der Informationen frei und sicher zwischen Teams fließen.",
      team: "Unser Team",
      teamSubtitle: "Eine leidenschaftliche Gruppe von Ingenieuren, Designern und Produktexperten.",
      values: "Unsere Werte",
      security: "Sicherheit Zuerst",
      securityDesc: "Jede Funktion wird mit Datenschutz als Kernprinzip entwickelt.",
      simplicity: "Radikale Einfachheit",
      simplicityDesc: "Leistungsstarke Funktionen, die jeder von Tag eins an nutzen kann.",
      reliability: "Immer Zuverlässig",
      reliabilityDesc: "99,9% Verfügbarkeits-SLA mit Enterprise-Infrastruktur.",
      innovation: "Kontinuierliche Innovation",
      innovationDesc: "Wir liefern wöchentlich Verbesserungen, basierend auf Nutzerfeedback.",
      stat1: "Verwaltete Dokumente",
      stat2: "Aktive Teams",
      stat3: "Länder",
      stat4: "Verfügbarkeit",
    },
    contact: {
      badge: "Kontaktieren Sie uns",
      title: "Wir würden uns freuen",
      titleHighlight: "von Ihnen zu hören",
      subtitle: "Fragen, Feedback oder einfach Hallo sagen? Unser Team ist für Sie da.",
      name: "Vollständiger Name",
      namePlaceholder: "Geben Sie Ihren Namen ein",
      email: "E-Mail-Adresse",
      emailPlaceholder: "sie@unternehmen.de",
      subject: "Betreff",
      subjectPlaceholder: "Wie können wir Ihnen helfen?",
      message: "Nachricht",
      messagePlaceholder: "Erzählen Sie uns mehr über Ihre Anfrage...",
      send: "Nachricht senden",
      sending: "Senden...",
      success: "Nachricht gesendet! Wir melden uns innerhalb von 24 Stunden.",
      info: "Kontaktinformationen",
      emailLabel: "E-Mail",
      phoneLabel: "Anrufen",
      addressLabel: "Büro",
      address: "123 Tech Park, Sektor 5, Mumbai 400001, Indien",
      hours: "Geschäftszeiten",
      hoursVal: "Mo – Fr, 9 – 18 Uhr IST",
    },
    footer: {
      privacy: "Datenschutzrichtlinie",
      terms: "Nutzungsbedingungen",
      support: "Support",
      contact: "Kontakt",
      rights: "Alle Rechte vorbehalten.",
    },
  },

  es: {
    nav: {
      home: "Inicio", features: "Características", solutions: "Soluciones",
      resources: "Recursos", about: "Nosotros", contact: "Contacto",
      getStarted: "Comenzar",
    },
    hero: {
      badge: "Inteligente. Seguro. Simplificado.",
      title: "Gestiona documentos",
      titleHighlight: "de forma más inteligente",
      subtitle: "Almacena, organiza y accede a todos tus documentos de forma segura desde una plataforma centralizada.",
      btnStart: "Comenzar",
      btnDemo: "Ver Demo",
      badge1: "Seguro y Cumplidor",
      badge2: "Acceso en Cualquier Lugar",
      badge3: "Solución Escalable",
    },
    about: {
      badge: "Nuestra Historia",
      title: "Construido para la gestión moderna",
      titleHighlight: "de documentos",
      subtitle: "Comenzamos DMS con una creencia simple — gestionar documentos debe ser fácil.",
      mission: "Nuestra Misión",
      missionText: "Empoderar a las organizaciones con una plataforma de gestión documental segura, inteligente y fácil de usar.",
      vision: "Nuestra Visión",
      visionText: "Un mundo donde la información fluye libre y seguramente entre equipos.",
      team: "Nuestro Equipo",
      teamSubtitle: "Un apasionado grupo de ingenieros, diseñadores y expertos en producto.",
      values: "Nuestros Valores",
      security: "Seguridad Primero",
      securityDesc: "Cada función está construida con la protección de datos en su núcleo.",
      simplicity: "Simplicidad Radical",
      simplicityDesc: "Funciones poderosas que cualquiera puede usar desde el primer día.",
      reliability: "Siempre Confiable",
      reliabilityDesc: "SLA de disponibilidad del 99,9% con infraestructura de nivel empresarial.",
      innovation: "Innovación Continua",
      innovationDesc: "Enviamos mejoras cada semana, impulsadas por los comentarios de los usuarios.",
      stat1: "Documentos Gestionados",
      stat2: "Equipos Activos",
      stat3: "Países",
      stat4: "Disponibilidad",
    },
    contact: {
      badge: "Ponte en contacto",
      title: "Nos encantaría",
      titleHighlight: "saber de ti",
      subtitle: "¿Tienes preguntas, comentarios o simplemente quieres decir hola? Nuestro equipo está aquí.",
      name: "Nombre Completo",
      namePlaceholder: "Ingresa tu nombre",
      email: "Correo Electrónico",
      emailPlaceholder: "tu@empresa.com",
      subject: "Asunto",
      subjectPlaceholder: "¿Cómo podemos ayudarte?",
      message: "Mensaje",
      messagePlaceholder: "Cuéntanos más sobre tu consulta...",
      send: "Enviar Mensaje",
      sending: "Enviando...",
      success: "¡Mensaje enviado! Te responderemos en 24 horas.",
      info: "Información de Contacto",
      emailLabel: "Escríbenos",
      phoneLabel: "Llámanos",
      addressLabel: "Oficina",
      address: "123 Tech Park, Sector 5, Mumbai 400001, India",
      hours: "Horario de Atención",
      hoursVal: "Lun – Vie, 9 AM – 6 PM IST",
    },
    footer: {
      privacy: "Política de Privacidad",
      terms: "Términos de Servicio",
      support: "Soporte",
      contact: "Contacto",
      rights: "Todos los derechos reservados.",
    },
  },

  ar: {
    nav: {
      home: "الرئيسية", features: "الميزات", solutions: "الحلول",
      resources: "الموارد", about: "من نحن", contact: "اتصل بنا",
      getStarted: "ابدأ الآن",
    },
    hero: {
      badge: "ذكي. آمن. مبسّط.",
      title: "إدارة المستندات",
      titleHighlight: "بشكل أذكى",
      subtitle: "خزّن ونظّم وصل إلى جميع مستنداتك بأمان من منصة مركزية واحدة.",
      btnStart: "ابدأ الآن",
      btnDemo: "شاهد العرض",
      badge1: "آمن ومتوافق",
      badge2: "الوصول من أي مكان",
      badge3: "حل قابل للتوسع",
    },
    about: {
      badge: "قصتنا",
      title: "مبنى للإدارة الحديثة",
      titleHighlight: "للمستندات",
      subtitle: "بدأنا DMS بقناعة بسيطة — إدارة المستندات يجب أن تكون سهلة.",
      mission: "مهمتنا",
      missionText: "تمكين المؤسسات بمنصة إدارة مستندات آمنة وذكية وسهلة الاستخدام.",
      vision: "رؤيتنا",
      visionText: "عالم تتدفق فيه المعلومات بحرية وأمان عبر الفرق.",
      team: "فريقنا",
      teamSubtitle: "مجموعة متحمسة من المهندسين والمصممين وخبراء المنتج.",
      values: "قيمنا",
      security: "الأمان أولاً",
      securityDesc: "كل ميزة مبنية مع حماية البيانات في صميمها.",
      simplicity: "البساطة الجذرية",
      simplicityDesc: "ميزات قوية يمكن لأي شخص استخدامها من اليوم الأول.",
      reliability: "موثوق دائماً",
      reliabilityDesc: "99.9% وقت تشغيل مع بنية تحتية على مستوى المؤسسة.",
      innovation: "ابتكار مستمر",
      innovationDesc: "نحسّن كل أسبوع بناءً على ملاحظات المستخدمين.",
      stat1: "مستند تمت إدارته",
      stat2: "فريق نشط",
      stat3: "دولة",
      stat4: "وقت التشغيل",
    },
    contact: {
      badge: "تواصل معنا",
      title: "يسعدنا",
      titleHighlight: "سماع منك",
      subtitle: "لديك أسئلة أو ملاحظات أو تريد فقط قول مرحبا؟ فريقنا هنا للمساعدة.",
      name: "الاسم الكامل",
      namePlaceholder: "أدخل اسمك",
      email: "البريد الإلكتروني",
      emailPlaceholder: "you@company.com",
      subject: "الموضوع",
      subjectPlaceholder: "كيف يمكننا المساعدة؟",
      message: "الرسالة",
      messagePlaceholder: "أخبرنا المزيد عن استفسارك...",
      send: "إرسال الرسالة",
      sending: "جارٍ الإرسال...",
      success: "تم إرسال الرسالة! سنرد عليك خلال 24 ساعة.",
      info: "معلومات الاتصال",
      emailLabel: "راسلنا",
      phoneLabel: "اتصل بنا",
      addressLabel: "المكتب",
      address: "123 تك بارك، القطاع 5، مومباي 400001، الهند",
      hours: "ساعات العمل",
      hoursVal: "الإثنين – الجمعة، 9 ص – 6 م IST",
    },
    footer: {
      privacy: "سياسة الخصوصية",
      terms: "شروط الخدمة",
      support: "الدعم",
      contact: "اتصل بنا",
      rights: "جميع الحقوق محفوظة.",
    },
  },

  zh: {
    nav: {
      home: "首页", features: "功能", solutions: "解决方案",
      resources: "资源", about: "关于我们", contact: "联系",
      getStarted: "开始使用",
    },
    hero: {
      badge: "智能。安全。简化。",
      title: "更智能地",
      titleHighlight: "管理文档",
      subtitle: "从一个集中平台安全地存储、组织和访问您的所有文档。",
      btnStart: "开始使用",
      btnDemo: "观看演示",
      badge1: "安全合规",
      badge2: "随时随地访问",
      badge3: "可扩展解决方案",
    },
    about: {
      badge: "我们的故事",
      title: "专为现代文档管理",
      titleHighlight: "而构建",
      subtitle: "我们以一个简单的信念创立了 DMS——管理文档应该毫不费力。",
      mission: "我们的使命",
      missionText: "为组织提供安全、智能、易用的文档管理平台，伴随其成长而扩展。",
      vision: "我们的愿景",
      visionText: "信息在团队之间自由、安全地流动——没有丢失的文件，没有版本混乱。",
      team: "团队介绍",
      teamSubtitle: "一群热情的工程师、设计师和产品专家，致力于构建优秀的软件。",
      values: "我们的价值观",
      security: "安全第一",
      securityDesc: "每个功能的核心都是数据保护。",
      simplicity: "极致简洁",
      simplicityDesc: "强大的功能，任何人从第一天起都能使用。",
      reliability: "始终可靠",
      reliabilityDesc: "99.9% 正常运行时间 SLA，企业级基础设施。",
      innovation: "持续创新",
      innovationDesc: "我们每周根据用户反馈进行改进。",
      stat1: "管理的文档",
      stat2: "活跃团队",
      stat3: "国家",
      stat4: "正常运行时间",
    },
    contact: {
      badge: "联系我们",
      title: "我们很乐意",
      titleHighlight: "听取您的意见",
      subtitle: "有问题、反馈或只是想打个招呼？我们的团队随时为您提供帮助。",
      name: "全名",
      namePlaceholder: "请输入您的姓名",
      email: "电子邮件地址",
      emailPlaceholder: "you@company.com",
      subject: "主题",
      subjectPlaceholder: "我们如何帮助您？",
      message: "消息",
      messagePlaceholder: "告诉我们更多关于您的问题...",
      send: "发送消息",
      sending: "发送中...",
      success: "消息已发送！我们将在 24 小时内回复您。",
      info: "联系信息",
      emailLabel: "发送邮件",
      phoneLabel: "致电我们",
      addressLabel: "办公室",
      address: "印度孟买 400001 第 5 区科技园 123 号",
      hours: "营业时间",
      hoursVal: "周一至周五，上午 9 时至下午 6 时 IST",
    },
    footer: {
      privacy: "隐私政策",
      terms: "服务条款",
      support: "支持",
      contact: "联系",
      rights: "版权所有。",
    },
  },

  ja: {
    nav: {
      home: "ホーム", features: "機能", solutions: "ソリューション",
      resources: "リソース", about: "会社概要", contact: "お問い合わせ",
      getStarted: "始める",
    },
    hero: {
      badge: "スマート。安全。シンプル。",
      title: "文書管理を",
      titleHighlight: "よりスマートに",
      subtitle: "すべての文書を一元化されたプラットフォームから安全に保存、整理、アクセスできます。",
      btnStart: "始める",
      btnDemo: "デモを見る",
      badge1: "安全でコンプライアント",
      badge2: "どこからでもアクセス",
      badge3: "スケーラブルなソリューション",
    },
    about: {
      badge: "私たちのストーリー",
      title: "現代的な文書管理のために",
      titleHighlight: "構築されました",
      subtitle: "私たちはシンプルな信念でDMSを始めました — 文書管理は簡単であるべきです。",
      mission: "私たちのミッション",
      missionText: "組織に安全でインテリジェントで使いやすい文書管理プラットフォームを提供すること。",
      vision: "私たちのビジョン",
      visionText: "情報がチーム間で自由かつ安全に流れる世界。",
      team: "チーム紹介",
      teamSubtitle: "エンジニア、デザイナー、プロダクト専門家の情熱的なグループ。",
      values: "私たちの価値観",
      security: "セキュリティ優先",
      securityDesc: "すべての機能はデータ保護を核心として構築されています。",
      simplicity: "徹底的なシンプルさ",
      simplicityDesc: "誰でも初日から使える強力な機能。",
      reliability: "常に信頼性",
      reliabilityDesc: "エンタープライズグレードのインフラで99.9%稼働時間SLA。",
      innovation: "継続的なイノベーション",
      innovationDesc: "ユーザーフィードバックに基づいて毎週改善を提供。",
      stat1: "管理された文書",
      stat2: "アクティブチーム",
      stat3: "国",
      stat4: "稼働時間",
    },
    contact: {
      badge: "お問い合わせ",
      title: "ぜひ",
      titleHighlight: "ご連絡ください",
      subtitle: "ご質問、フィードバック、またはただご挨拶でも？私たちのチームがお手伝いします。",
      name: "フルネーム",
      namePlaceholder: "お名前を入力してください",
      email: "メールアドレス",
      emailPlaceholder: "you@company.com",
      subject: "件名",
      subjectPlaceholder: "どのようにお手伝いできますか？",
      message: "メッセージ",
      messagePlaceholder: "お問い合わせの詳細をお聞かせください...",
      send: "メッセージを送る",
      sending: "送信中...",
      success: "メッセージが送信されました！24時間以内にご返信いたします。",
      info: "連絡先情報",
      emailLabel: "メールで連絡",
      phoneLabel: "電話で連絡",
      addressLabel: "オフィス",
      address: "インド、ムンバイ400001、セクター5、テックパーク123",
      hours: "営業時間",
      hoursVal: "月 – 金、午前9時 – 午後6時 IST",
    },
    footer: {
      privacy: "プライバシーポリシー",
      terms: "利用規約",
      support: "サポート",
      contact: "お問い合わせ",
      rights: "全著作権所有。",
    },
  },
};

// Fallback: missing lang → English
const getTranslations = (lang) => translations[lang] || translations["en"];

// ── Context ──
const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem("dms_lang") || "en";
  });

  const changeLang = (code) => {
    setLang(code);
    localStorage.setItem("dms_lang", code);
  };

  const t = (key) => {
    const keys = key.split(".");
    let val = getTranslations(lang);
    for (const k of keys) {
      val = val?.[k];
      if (val === undefined) return key; // fallback to key
    }
    return val;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t, languages }}>
      <div dir={lang === "ar" ? "rtl" : "ltr"}>{children}</div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside <LanguageProvider>");
  return ctx;
}